# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-02 15:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dinosaur',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('height', models.FloatField(default=0.0)),
                ('birth_date', models.DateTimeField(verbose_name='birth date')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
    ]
