# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-02 16:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webr', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rental',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rental_date', models.DateField(verbose_name='rental date')),
                ('email', models.CharField(max_length=150)),
                ('rented_dino', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webr.Dinosaur')),
            ],
        ),
    ]
